service: play
runtime: custom
env: flex

resources:
  cpu: 2
  memory_gb: 2

automatic_scaling:
  min_num_instances: 1

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 10

env_variables:
  MEMCACHED_ADDR: 'memcached:11211'
